
#define STRINGIFY(x) STRING(x)
#define STRING(VER) #VER

// cppcheck version
#define CPPCHECK_MAJOR 2
#define CPPCHECK_MINOR 0
#define CPPCHECK_DEVMINOR 0

#if CPPCHECK_MINOR == CPPCHECK_DEVMINOR
#define FULL_VERSION_STRING STRINGIFY(CPPCHECK_MAJOR) "." STRINGIFY(CPPCHECK_MINOR)
#define FULL_VERSION CPPCHECK_MAJOR,CPPCHECK_MINOR
#else
#define FULL_VERSION_STRING STRINGIFY(CPPCHECK_MAJOR) "." STRINGIFY(CPPCHECK_DEVMINOR) "d"
#define FULL_VERSION CPPCHECK_MAJOR,CPPCHECK_MINOR
#endif

